set shell := ["zsh", "-cu"]

default:
  @just --list

install:
  poetry install

run env="local" debug="true":
  poetry run python main.py --env {{env}} {{ if debug == "true" { "--debug" } else { "" } }}

test:
  ENV=test poetry run pytest tests -s

cov:
  ENV=test poetry run coverage run -m pytest
  poetry run coverage html

up:
  docker compose -f docker/docker-compose.yml up -d

down:
  docker compose -f docker/docker-compose.yml down

migrate:
  poetry run alembic upgrade head

migrate-db db_url:
  MIGRATION_DB_URL={{db_url}} poetry run alembic upgrade head

migrate-local:
  WRITER_DB_URL=mysql+aiomysql://fastapi:fastapi@localhost:3306/fastapi poetry run alembic upgrade head

migrate-test:
  ENV=test poetry run alembic upgrade head

revision message:
  poetry run alembic revision --autogenerate -m "{{message}}"

revision-empty message:
  poetry run alembic revision -m "{{message}}"
