"""message=add alert device driver vehicle ids

Revision ID: 0c55f03c58a8
Revises: 3e4960f385a7
Create Date: 2026-03-24 21:40:12.327770

"""

from alembic import op
import sqlalchemy as sa

from infrastructure.db.models import PG_VIEWS


# revision identifiers, used by Alembic.
revision = "0c55f03c58a8"
down_revision = "3e4960f385a7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "alert", sa.Column("device_id", sa.UUID(), nullable=False), schema="alert"
    )
    op.add_column(
        "alert", sa.Column("driver_id", sa.UUID(), nullable=True), schema="alert"
    )
    op.add_column(
        "alert", sa.Column("vehicle_id", sa.UUID(), nullable=True), schema="alert"
    )

    for view_def in PG_VIEWS:
        op.execute(sa.text(view_def.drop_sql()))

    for view_def in PG_VIEWS:
        op.execute(sa.text(view_def.create_sql()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("alert", "vehicle_id", schema="alert")
    op.drop_column("alert", "driver_id", schema="alert")
    op.drop_column("alert", "device_id", schema="alert")

    for view_def in PG_VIEWS:
        op.execute(sa.text(view_def.drop_sql()))

    for view_def in PG_VIEWS:
        op.execute(sa.text(view_def.create_sql()))
    # ### end Alembic commands ###
