"""message=auto

Revision ID: 110cf0f2ec6b
Revises: 9a1d8b3f6c21
Create Date: 2026-05-06 05:16:25.435007

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '110cf0f2ec6b'
down_revision = '9a1d8b3f6c21'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
