"""message=add user profile name and address fields

Revision ID: 11c76830e642
Revises: 1af62fd34a48
Create Date: 2026-03-24 21:52:40.239382

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '11c76830e642'
down_revision = '1af62fd34a48'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
