"""message=add user profile name and address fields

Revision ID: 1af62fd34a48
Revises: 0c55f03c58a8
Create Date: 2026-03-24 21:47:04.294057

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '1af62fd34a48'
down_revision = '0c55f03c58a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name__family', sa.String(), nullable=True), schema='user')
    op.add_column('user', sa.Column('name__given', sa.String(), nullable=True), schema='user')
    op.add_column('user', sa.Column('name__middle', sa.String(), nullable=True), schema='user')
    op.add_column('user', sa.Column('name__prefix', sa.String(), nullable=True), schema='user')
    op.add_column('user', sa.Column('name__suffix', sa.String(), nullable=True), schema='user')
    op.add_column('user', sa.Column('birthday', sa.Date(), nullable=True), schema='user')
    op.add_column('user', sa.Column('gender', sa.String(), nullable=True), schema='user')
    op.add_column('user', sa.Column('address__city', sa.String(), nullable=True), schema='user')
    op.add_column('user', sa.Column('address__country', sa.String(), nullable=True), schema='user')
    op.add_column('user', sa.Column('address__line1', sa.String(), nullable=True), schema='user')
    op.add_column('user', sa.Column('address__line2', sa.String(), nullable=True), schema='user')
    op.drop_constraint(op.f('user_email_key'), 'user', schema='user', type_='unique')
    op.drop_index(op.f('ix_user_user_email'), table_name='user', schema='user')
    op.create_index(op.f('ix_user_user_email'), 'user', ['email'], unique=True, schema='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_user_email'), table_name='user', schema='user')
    op.create_index(op.f('ix_user_user_email'), 'user', ['email'], unique=False, schema='user')
    op.create_unique_constraint(op.f('user_email_key'), 'user', ['email'], schema='user', postgresql_nulls_not_distinct=False)
    op.drop_column('user', 'address__line2', schema='user')
    op.drop_column('user', 'address__line1', schema='user')
    op.drop_column('user', 'address__country', schema='user')
    op.drop_column('user', 'address__city', schema='user')
    op.drop_column('user', 'gender', schema='user')
    op.drop_column('user', 'birthday', schema='user')
    op.drop_column('user', 'name__suffix', schema='user')
    op.drop_column('user', 'name__prefix', schema='user')
    op.drop_column('user', 'name__middle', schema='user')
    op.drop_column('user', 'name__given', schema='user')
    op.drop_column('user', 'name__family', schema='user')
    # ### end Alembic commands ###
