"""alert uuid and behavior fields

Revision ID: 20260324_0004
Revises: 20260324_0003
Create Date: 2026-03-24 01:40:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from infrastructure.db.models import PG_VIEWS


# revision identifiers, used by Alembic.
revision: str = "20260324_0004"
down_revision: Union[str, Sequence[str], None] = "20260324_0003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(sa.text('DROP VIEW IF EXISTS "alert"._alert_overview'))
    op.execute(sa.text('DROP VIEW IF EXISTS "alert".v_alert_overview'))

    op.execute(sa.text('CREATE EXTENSION IF NOT EXISTS "pgcrypto"'))
    op.execute(
        sa.text(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_type t
                    JOIN pg_namespace n ON n.oid = t.typnamespace
                    WHERE t.typname = 'alert_type_enum' AND n.nspname = 'alert'
                ) THEN
                    CREATE TYPE "alert".alert_type_enum AS ENUM (
                        'SLEEPING',
                        'USING_PHONE',
                        'DISTRACTED'
                    );
                END IF;
            END
            $$;
            """
        )
    )

    op.execute(
        sa.text(
            'ALTER TABLE "alert"."alert" ADD COLUMN IF NOT EXISTS id_uuid UUID DEFAULT gen_random_uuid()'
        )
    )
    op.execute(
        sa.text(
            'UPDATE "alert"."alert" SET id_uuid = gen_random_uuid() WHERE id_uuid IS NULL'
        )
    )
    op.execute(sa.text('ALTER TABLE "alert"."alert" ALTER COLUMN id_uuid SET NOT NULL'))

    op.execute(
        sa.text('ALTER TABLE "alert"."alert" DROP CONSTRAINT IF EXISTS alert_pkey')
    )
    op.execute(sa.text('DROP INDEX IF EXISTS "alert".ix_alert_alert_id'))
    op.execute(sa.text('ALTER TABLE "alert"."alert" DROP COLUMN IF EXISTS id'))
    op.execute(sa.text('ALTER TABLE "alert"."alert" RENAME COLUMN id_uuid TO id'))
    op.execute(
        sa.text(
            'ALTER TABLE "alert"."alert" ADD CONSTRAINT alert_pkey PRIMARY KEY (id)'
        )
    )
    op.execute(
        sa.text('CREATE INDEX IF NOT EXISTS ix_alert_alert_id ON "alert"."alert" (id)')
    )

    op.execute(
        sa.text(
            'ALTER TABLE "alert"."alert" '
            'ADD COLUMN IF NOT EXISTS alert_type "alert".alert_type_enum '
            "NOT NULL DEFAULT 'DISTRACTED'"
        )
    )
    op.execute(
        sa.text(
            'ALTER TABLE "alert"."alert" ADD COLUMN IF NOT EXISTS evidence_url VARCHAR'
        )
    )
    op.execute(
        sa.text(
            'ALTER TABLE "alert"."alert" ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION'
        )
    )
    op.execute(
        sa.text(
            'ALTER TABLE "alert"."alert" ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION'
        )
    )

    for view_def in PG_VIEWS:
        op.execute(sa.text(view_def.create_sql()))


def downgrade() -> None:
    op.execute(sa.text('DROP VIEW IF EXISTS "alert".v_alert_overview'))

    op.execute(sa.text('ALTER TABLE "alert"."alert" DROP COLUMN IF EXISTS longitude'))
    op.execute(sa.text('ALTER TABLE "alert"."alert" DROP COLUMN IF EXISTS latitude'))
    op.execute(
        sa.text('ALTER TABLE "alert"."alert" DROP COLUMN IF EXISTS evidence_url')
    )
    op.execute(sa.text('ALTER TABLE "alert"."alert" DROP COLUMN IF EXISTS alert_type'))

    op.execute(
        sa.text('ALTER TABLE "alert"."alert" DROP CONSTRAINT IF EXISTS alert_pkey')
    )
    op.execute(sa.text('DROP INDEX IF EXISTS "alert".ix_alert_alert_id'))
    op.execute(sa.text('ALTER TABLE "alert"."alert" RENAME COLUMN id TO id_uuid'))
    op.execute(
        sa.text(
            'ALTER TABLE "alert"."alert" ADD COLUMN id INTEGER GENERATED BY DEFAULT AS IDENTITY'
        )
    )
    op.execute(
        sa.text(
            'ALTER TABLE "alert"."alert" ADD CONSTRAINT alert_pkey PRIMARY KEY (id)'
        )
    )
    op.execute(
        sa.text('CREATE INDEX IF NOT EXISTS ix_alert_alert_id ON "alert"."alert" (id)')
    )
    op.execute(sa.text('ALTER TABLE "alert"."alert" DROP COLUMN IF EXISTS id_uuid'))

    op.execute(sa.text('DROP TYPE IF EXISTS "alert".alert_type_enum'))

    for view_def in PG_VIEWS:
        op.execute(sa.text(view_def.create_sql()))
