"""auto

Revision ID: 22d72a301c78
Revises: 1e1b788f4852
Create Date: 2026-04-01 23:06:38.204516

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '22d72a301c78'
down_revision = '1e1b788f4852'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
