"""add_vehicle_device_id

Revision ID: 35003fae62f9
Revises: 72bfa691061d
Create Date: 2026-06-01 18:15:32.055819

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '35003fae62f9'
down_revision = '72bfa691061d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('device_id', sa.UUID(), nullable=True), schema='vehicle')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle', 'device_id', schema='vehicle')
    # ### end Alembic commands ###
