"""message=add_fingerprint_and_driving_session

Revision ID: 3ec15751b588
Revises: 9bd671df154f
Create Date: 2026-05-06 07:27:25.509214

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '3ec15751b588'
down_revision = '9bd671df154f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driving_session',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('_deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user._id'], ),
    sa.PrimaryKeyConstraint('_id'),
    schema='user'
    )
    op.create_index(op.f('ix_user_driving_session__id'), 'driving_session', ['_id'], unique=False, schema='user')
    op.create_index(op.f('ix_user_driving_session_user_id'), 'driving_session', ['user_id'], unique=False, schema='user')
    op.add_column('user', sa.Column('fingerprint_id', sa.String(), nullable=True), schema='user')
    op.create_index(op.f('ix_user_user_fingerprint_id'), 'user', ['fingerprint_id'], unique=True, schema='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_user_fingerprint_id'), table_name='user', schema='user')
    op.drop_column('user', 'fingerprint_id', schema='user')
    op.drop_index(op.f('ix_user_driving_session_user_id'), table_name='driving_session', schema='user')
    op.drop_index(op.f('ix_user_driving_session__id'), table_name='driving_session', schema='user')
    op.drop_table('driving_session', schema='user')
    # ### end Alembic commands ###
