"""schema user

Revision ID: 570b0ab9d1a2
Revises: 20260324_0002
Create Date: 2026-03-24 15:29:31.498679

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "570b0ab9d1a2"
down_revision = "20260324_0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use IF EXISTS to avoid errors when indexes are already absent
    op.execute('DROP INDEX IF EXISTS "user".ix_user_email')
    op.execute('DROP INDEX IF EXISTS "user".ix_user_id')
    # Create indexes only if they do not already exist to avoid duplicate errors
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_indexes WHERE schemaname = 'user' AND indexname = 'ix_user_user_email'
            ) THEN
                CREATE UNIQUE INDEX ix_user_user_email ON "user"."user" (email);
            END IF;
        END
        $$;
        """
    )
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_indexes WHERE schemaname = 'user' AND indexname = 'ix_user_user_id'
            ) THEN
                CREATE INDEX ix_user_user_id ON "user"."user" (id);
            END IF;
        END
        $$;
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_user_id"), table_name="user", schema="user")
    op.drop_index(op.f("ix_user_user_email"), table_name="user", schema="user")
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False, schema="user")
    op.create_index(
        op.f("ix_user_email"), "user", ["email"], unique=True, schema="user"
    )
    # ### end Alembic commands ###
