"""message=add_ended_at

Revision ID: 72bfa691061d
Revises: 3ec15751b588
Create Date: 2026-05-06 07:36:35.174424

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '72bfa691061d'
down_revision = '3ec15751b588'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driving_session', sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True), schema='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driving_session', 'ended_at', schema='user')
    # ### end Alembic commands ###
