"""schema alert

Revision ID: a44561f72999
Revises: 570b0ab9d1a2
Create Date: 2026-03-24 15:33:30.037565

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a44561f72999"
down_revision = "570b0ab9d1a2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text('CREATE SCHEMA IF NOT EXISTS "alert"'))
    # Create table only if it does not exist to avoid DuplicateTable errors
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.tables
                WHERE table_schema = 'alert' AND table_name = 'alert'
            ) THEN
                CREATE TABLE "alert"."alert" (
                    id SERIAL NOT NULL,
                    message VARCHAR NOT NULL,
                    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                    PRIMARY KEY (id)
                );
            END IF;
        END
        $$;
        """
    )
    # Create index only if it does not already exist
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_indexes WHERE schemaname = 'alert' AND indexname = 'ix_alert_alert_id'
            ) THEN
                CREATE INDEX ix_alert_alert_id ON "alert"."alert" (id);
            END IF;
        END
        $$;
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_alert_alert_id"), table_name="alert", schema="alert")
    op.drop_table("alert", schema="alert")
    op.execute(sa.text('DROP SCHEMA IF EXISTS "alert"'))
    # ### end Alembic commands ###
