"""auto

Revision ID: b86cf1f0dd45
Revises: 110cf0f2ec6b
Create Date: 2026-05-06 05:20:14.071607

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'b86cf1f0dd45'
down_revision = '110cf0f2ec6b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
