"""init_db

Revision ID: 944a7151a4d8
Revises: 5bd3995ceffa
Create Date: 2026-04-02 23:08:43.334058

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '944a7151a4d8'
down_revision = '5bd3995ceffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
