platform :ios, '14.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386'
    end
  end

  debug_xcconfig = File.join(__dir__, 'Pods', 'Target Support Files', 'Pods-Runner', 'Pods-Runner.debug.xcconfig')
  if File.exist?(debug_xcconfig)
    content = File.read(debug_xcconfig)
    content.gsub!(' -framework "ffmpeg_kit_flutter_new_min_gpl"', '')
    content.gsub!(' -framework "ffmpegkit"', '')
    content.gsub!(' -framework "libavcodec"', '')
    content.gsub!(' -framework "libavdevice"', '')
    content.gsub!(' -framework "libavfilter"', '')
    content.gsub!(' -framework "libavformat"', '')
    content.gsub!(' -framework "libavutil"', '')
    content.gsub!(' -framework "libswresample"', '')
    content.gsub!(' -framework "libswscale"', '')
    File.write(debug_xcconfig, content)
  end

  registrant = File.join(__dir__, 'Runner', 'GeneratedPluginRegistrant.m')
  if File.exist?(registrant)
    registrant_content = File.read(registrant)
    unless registrant_content.include?('ROADSENTINEL_SIMULATOR_FFMPEG_GUARD')
      registrant_content.sub!(
        '#import "GeneratedPluginRegistrant.h"',
        "#import \"GeneratedPluginRegistrant.h\"\n#import <TargetConditionals.h>"
      )
      registrant_content.sub!(
        "#if __has_include(<ffmpeg_kit_flutter_new_min_gpl/FFmpegKitFlutterPlugin.h>)\n#import <ffmpeg_kit_flutter_new_min_gpl/FFmpegKitFlutterPlugin.h>\n#else\n@import ffmpeg_kit_flutter_new_min_gpl;\n#endif",
        "// ROADSENTINEL_SIMULATOR_FFMPEG_GUARD\n#if !TARGET_OS_SIMULATOR\n#if __has_include(<ffmpeg_kit_flutter_new_min_gpl/FFmpegKitFlutterPlugin.h>)\n#import <ffmpeg_kit_flutter_new_min_gpl/FFmpegKitFlutterPlugin.h>\n#else\n@import ffmpeg_kit_flutter_new_min_gpl;\n#endif\n#endif"
      )
      registrant_content.sub!(
        "  [FFmpegKitFlutterPlugin registerWithRegistrar:[registry registrarForPlugin:\"FFmpegKitFlutterPlugin\"]];",
        "#if !TARGET_OS_SIMULATOR\n  [FFmpegKitFlutterPlugin registerWithRegistrar:[registry registrarForPlugin:\"FFmpegKitFlutterPlugin\"]];\n#endif"
      )
      registrant_content.gsub!(
        /\s*\[FFmpegKitFlutterPlugin registerWithRegistrar:\[registry registrarForPlugin:@\"FFmpegKitFlutterPlugin\"\]\];/,
        "\n#if !TARGET_OS_SIMULATOR\n  [FFmpegKitFlutterPlugin registerWithRegistrar:[registry registrarForPlugin:\"FFmpegKitFlutterPlugin\"]];\n#endif"
      )
      File.write(registrant, registrant_content)
    end
  end
end
